<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'rapture\\adr\\action' => '/../src/Action.php',
                'rapture\\adr\\dispatcher' => '/../src/Dispatcher.php',
                'rapture\\adr\\handler' => '/../src/Handler.php',
                'rapture\\adr\\jsonresponder' => '/../src/JsonResponder.php',
                'rapture\\adr\\responder' => '/../src/Responder.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
